//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JInterchageModel", Namespace="http://schemas.datacontract.org/2004/07/ISCIII.AESEG.JustificationService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JpersonalInterchageModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JviajeInterchageModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JbsInterchageModel))]
    public partial class JInterchageModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AnualidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpedienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteImputadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idConceptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoJustificanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Anualidad {
            get {
                return this.AnualidadField;
            }
            set {
                if ((this.AnualidadField.Equals(value) != true)) {
                    this.AnualidadField = value;
                    this.RaisePropertyChanged("Anualidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expediente {
            get {
                return this.ExpedienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpedienteField, value) != true)) {
                    this.ExpedienteField = value;
                    this.RaisePropertyChanged("Expediente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPartida {
            get {
                return this.IdPartidaField;
            }
            set {
                if ((this.IdPartidaField.Equals(value) != true)) {
                    this.IdPartidaField = value;
                    this.RaisePropertyChanged("IdPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImporteImputado {
            get {
                return this.ImporteImputadoField;
            }
            set {
                if ((this.ImporteImputadoField.Equals(value) != true)) {
                    this.ImporteImputadoField = value;
                    this.RaisePropertyChanged("ImporteImputado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ImporteTotal {
            get {
                return this.ImporteTotalField;
            }
            set {
                if ((this.ImporteTotalField.Equals(value) != true)) {
                    this.ImporteTotalField = value;
                    this.RaisePropertyChanged("ImporteTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idConcepto {
            get {
                return this.idConceptoField;
            }
            set {
                if ((this.idConceptoField.Equals(value) != true)) {
                    this.idConceptoField = value;
                    this.RaisePropertyChanged("idConcepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoJustificante {
            get {
                return this.idTipoJustificanteField;
            }
            set {
                if ((this.idTipoJustificanteField.Equals(value) != true)) {
                    this.idTipoJustificanteField = value;
                    this.RaisePropertyChanged("idTipoJustificante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JpersonalInterchageModel", Namespace="http://schemas.datacontract.org/2004/07/ISCIII.AESEG.JustificationService")]
    [System.SerializableAttribute()]
    public partial class JpersonalInterchageModel : ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JInterchageModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiasBajaITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDesdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHastaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroPerNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroPerOtrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroPerPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaLaboralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroPerNominaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroPerOtrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroPerPagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiasBajaIT {
            get {
                return this.DiasBajaITField;
            }
            set {
                if ((this.DiasBajaITField.Equals(value) != true)) {
                    this.DiasBajaITField = value;
                    this.RaisePropertyChanged("DiasBajaIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDesde {
            get {
                return this.FechaDesdeField;
            }
            set {
                if ((this.FechaDesdeField.Equals(value) != true)) {
                    this.FechaDesdeField = value;
                    this.RaisePropertyChanged("FechaDesde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHasta {
            get {
                return this.FechaHastaField;
            }
            set {
                if ((this.FechaHastaField.Equals(value) != true)) {
                    this.FechaHastaField = value;
                    this.RaisePropertyChanged("FechaHasta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroPerNomina {
            get {
                return this.FicheroPerNominaField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroPerNominaField, value) != true)) {
                    this.FicheroPerNominaField = value;
                    this.RaisePropertyChanged("FicheroPerNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroPerOtros {
            get {
                return this.FicheroPerOtrosField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroPerOtrosField, value) != true)) {
                    this.FicheroPerOtrosField = value;
                    this.RaisePropertyChanged("FicheroPerOtros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroPerPago {
            get {
                return this.FicheroPerPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroPerPagoField, value) != true)) {
                    this.FicheroPerPagoField = value;
                    this.RaisePropertyChanged("FicheroPerPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoriaLaboral {
            get {
                return this.IdCategoriaLaboralField;
            }
            set {
                if ((this.IdCategoriaLaboralField.Equals(value) != true)) {
                    this.IdCategoriaLaboralField = value;
                    this.RaisePropertyChanged("IdCategoriaLaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nif {
            get {
                return this.NifField;
            }
            set {
                if ((object.ReferenceEquals(this.NifField, value) != true)) {
                    this.NifField = value;
                    this.RaisePropertyChanged("Nif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroPerNomina {
            get {
                return this.NombreFicheroPerNominaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroPerNominaField, value) != true)) {
                    this.NombreFicheroPerNominaField = value;
                    this.RaisePropertyChanged("NombreFicheroPerNomina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroPerOtros {
            get {
                return this.NombreFicheroPerOtrosField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroPerOtrosField, value) != true)) {
                    this.NombreFicheroPerOtrosField = value;
                    this.RaisePropertyChanged("NombreFicheroPerOtros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroPerPago {
            get {
                return this.NombreFicheroPerPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroPerPagoField, value) != true)) {
                    this.NombreFicheroPerPagoField = value;
                    this.RaisePropertyChanged("NombreFicheroPerPago");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JviajeInterchageModel", Namespace="http://schemas.datacontract.org/2004/07/ISCIII.AESEG.JustificationService")]
    [System.SerializableAttribute()]
    public partial class JviajeInterchageModel : ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JInterchageModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BaseImponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptoFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinCongresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioCongresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroViajeFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroViajeOtrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroViajePagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTipoGastoViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTipoViajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItinerarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NifProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroViajeFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroViajeOtrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroViajePagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TipoImpositivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BaseImponible {
            get {
                return this.BaseImponibleField;
            }
            set {
                if ((this.BaseImponibleField.Equals(value) != true)) {
                    this.BaseImponibleField = value;
                    this.RaisePropertyChanged("BaseImponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroDestino {
            get {
                return this.CentroDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroDestinoField, value) != true)) {
                    this.CentroDestinoField = value;
                    this.RaisePropertyChanged("CentroDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConceptoFactura {
            get {
                return this.ConceptoFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoFacturaField, value) != true)) {
                    this.ConceptoFacturaField = value;
                    this.RaisePropertyChanged("ConceptoFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((this.FechaFacturaField.Equals(value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinCongreso {
            get {
                return this.FechaFinCongresoField;
            }
            set {
                if ((this.FechaFinCongresoField.Equals(value) != true)) {
                    this.FechaFinCongresoField = value;
                    this.RaisePropertyChanged("FechaFinCongreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinViaje {
            get {
                return this.FechaFinViajeField;
            }
            set {
                if ((this.FechaFinViajeField.Equals(value) != true)) {
                    this.FechaFinViajeField = value;
                    this.RaisePropertyChanged("FechaFinViaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicioCongreso {
            get {
                return this.FechaInicioCongresoField;
            }
            set {
                if ((this.FechaInicioCongresoField.Equals(value) != true)) {
                    this.FechaInicioCongresoField = value;
                    this.RaisePropertyChanged("FechaInicioCongreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicioViaje {
            get {
                return this.FechaInicioViajeField;
            }
            set {
                if ((this.FechaInicioViajeField.Equals(value) != true)) {
                    this.FechaInicioViajeField = value;
                    this.RaisePropertyChanged("FechaInicioViaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroViajeFactura {
            get {
                return this.FicheroViajeFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroViajeFacturaField, value) != true)) {
                    this.FicheroViajeFacturaField = value;
                    this.RaisePropertyChanged("FicheroViajeFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroViajeOtros {
            get {
                return this.FicheroViajeOtrosField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroViajeOtrosField, value) != true)) {
                    this.FicheroViajeOtrosField = value;
                    this.RaisePropertyChanged("FicheroViajeOtros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroViajePago {
            get {
                return this.FicheroViajePagoField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroViajePagoField, value) != true)) {
                    this.FicheroViajePagoField = value;
                    this.RaisePropertyChanged("FicheroViajePago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPaisField, value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTipoGastoViaje {
            get {
                return this.IdTipoGastoViajeField;
            }
            set {
                if ((this.IdTipoGastoViajeField.Equals(value) != true)) {
                    this.IdTipoGastoViajeField = value;
                    this.RaisePropertyChanged("IdTipoGastoViaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTipoViaje {
            get {
                return this.IdTipoViajeField;
            }
            set {
                if ((this.IdTipoViajeField.Equals(value) != true)) {
                    this.IdTipoViajeField = value;
                    this.RaisePropertyChanged("IdTipoViaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Itinerario {
            get {
                return this.ItinerarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ItinerarioField, value) != true)) {
                    this.ItinerarioField = value;
                    this.RaisePropertyChanged("Itinerario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nif {
            get {
                return this.NifField;
            }
            set {
                if ((object.ReferenceEquals(this.NifField, value) != true)) {
                    this.NifField = value;
                    this.RaisePropertyChanged("Nif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NifProveedor {
            get {
                return this.NifProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.NifProveedorField, value) != true)) {
                    this.NifProveedorField = value;
                    this.RaisePropertyChanged("NifProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroViajeFactura {
            get {
                return this.NombreFicheroViajeFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroViajeFacturaField, value) != true)) {
                    this.NombreFicheroViajeFacturaField = value;
                    this.RaisePropertyChanged("NombreFicheroViajeFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroViajeOtros {
            get {
                return this.NombreFicheroViajeOtrosField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroViajeOtrosField, value) != true)) {
                    this.NombreFicheroViajeOtrosField = value;
                    this.RaisePropertyChanged("NombreFicheroViajeOtros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroViajePago {
            get {
                return this.NombreFicheroViajePagoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroViajePagoField, value) != true)) {
                    this.NombreFicheroViajePagoField = value;
                    this.RaisePropertyChanged("NombreFicheroViajePago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProveedor {
            get {
                return this.NombreProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProveedorField, value) != true)) {
                    this.NombreProveedorField = value;
                    this.RaisePropertyChanged("NombreProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura {
            get {
                return this.NumeroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroFacturaField, value) != true)) {
                    this.NumeroFacturaField = value;
                    this.RaisePropertyChanged("NumeroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TipoImpositivo {
            get {
                return this.TipoImpositivoField;
            }
            set {
                if ((this.TipoImpositivoField.Equals(value) != true)) {
                    this.TipoImpositivoField = value;
                    this.RaisePropertyChanged("TipoImpositivo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JbsInterchageModel", Namespace="http://schemas.datacontract.org/2004/07/ISCIII.AESEG.JustificationService")]
    [System.SerializableAttribute()]
    public partial class JbsInterchageModel : ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JInterchageModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BaseImponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionConceptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroBSFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroBSOtrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FicheroBSPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroBSFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroBSOtrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFicheroBSPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TipoImpositivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BaseImponible {
            get {
                return this.BaseImponibleField;
            }
            set {
                if ((this.BaseImponibleField.Equals(value) != true)) {
                    this.BaseImponibleField = value;
                    this.RaisePropertyChanged("BaseImponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionConcepto {
            get {
                return this.DescripcionConceptoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionConceptoField, value) != true)) {
                    this.DescripcionConceptoField = value;
                    this.RaisePropertyChanged("DescripcionConcepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((this.FechaFacturaField.Equals(value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroBSFactura {
            get {
                return this.FicheroBSFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroBSFacturaField, value) != true)) {
                    this.FicheroBSFacturaField = value;
                    this.RaisePropertyChanged("FicheroBSFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroBSOtros {
            get {
                return this.FicheroBSOtrosField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroBSOtrosField, value) != true)) {
                    this.FicheroBSOtrosField = value;
                    this.RaisePropertyChanged("FicheroBSOtros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FicheroBSPago {
            get {
                return this.FicheroBSPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroBSPagoField, value) != true)) {
                    this.FicheroBSPagoField = value;
                    this.RaisePropertyChanged("FicheroBSPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIF {
            get {
                return this.NIFField;
            }
            set {
                if ((object.ReferenceEquals(this.NIFField, value) != true)) {
                    this.NIFField = value;
                    this.RaisePropertyChanged("NIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroBSFactura {
            get {
                return this.NombreFicheroBSFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroBSFacturaField, value) != true)) {
                    this.NombreFicheroBSFacturaField = value;
                    this.RaisePropertyChanged("NombreFicheroBSFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroBSOtros {
            get {
                return this.NombreFicheroBSOtrosField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroBSOtrosField, value) != true)) {
                    this.NombreFicheroBSOtrosField = value;
                    this.RaisePropertyChanged("NombreFicheroBSOtros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFicheroBSPago {
            get {
                return this.NombreFicheroBSPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFicheroBSPagoField, value) != true)) {
                    this.NombreFicheroBSPagoField = value;
                    this.RaisePropertyChanged("NombreFicheroBSPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProveedor {
            get {
                return this.NombreProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreProveedorField, value) != true)) {
                    this.NombreProveedorField = value;
                    this.RaisePropertyChanged("NombreProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura {
            get {
                return this.NumeroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroFacturaField, value) != true)) {
                    this.NumeroFacturaField = value;
                    this.RaisePropertyChanged("NumeroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TipoImpositivo {
            get {
                return this.TipoImpositivoField;
            }
            set {
                if ((this.TipoImpositivoField.Equals(value) != true)) {
                    this.TipoImpositivoField = value;
                    this.RaisePropertyChanged("TipoImpositivo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadResult", Namespace="http://schemas.datacontract.org/2004/07/ISCIII.AESEG.JustificationService")]
    [System.SerializableAttribute()]
    public partial class LoadResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnualidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JError[] ErroresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpedienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdJustificanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.ResultadoCarga ResultadoCargaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anualidad {
            get {
                return this.AnualidadField;
            }
            set {
                if ((this.AnualidadField.Equals(value) != true)) {
                    this.AnualidadField = value;
                    this.RaisePropertyChanged("Anualidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionResultado {
            get {
                return this.DescripcionResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionResultadoField, value) != true)) {
                    this.DescripcionResultadoField = value;
                    this.RaisePropertyChanged("DescripcionResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JError[] Errores {
            get {
                return this.ErroresField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroresField, value) != true)) {
                    this.ErroresField = value;
                    this.RaisePropertyChanged("Errores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expediente {
            get {
                return this.ExpedienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpedienteField, value) != true)) {
                    this.ExpedienteField = value;
                    this.RaisePropertyChanged("Expediente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdJustificante {
            get {
                return this.IdJustificanteField;
            }
            set {
                if ((this.IdJustificanteField.Equals(value) != true)) {
                    this.IdJustificanteField = value;
                    this.RaisePropertyChanged("IdJustificante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPartida {
            get {
                return this.IdPartidaField;
            }
            set {
                if ((this.IdPartidaField.Equals(value) != true)) {
                    this.IdPartidaField = value;
                    this.RaisePropertyChanged("IdPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.ResultadoCarga ResultadoCarga {
            get {
                return this.ResultadoCargaField;
            }
            set {
                if ((this.ResultadoCargaField.Equals(value) != true)) {
                    this.ResultadoCargaField = value;
                    this.RaisePropertyChanged("ResultadoCarga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JError", Namespace="http://schemas.datacontract.org/2004/07/ISCIII.AESEG.JustificationService")]
    [System.SerializableAttribute()]
    public partial class JError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoCarga", Namespace="http://schemas.datacontract.org/2004/07/ISCIII.AESEG.JustificationService")]
    public enum ResultadoCarga : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correcto = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erroneo = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aeseg.isciii.es", ConfigurationName="ProxyJustificacion.IJustification")]
    public interface IJustification {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/LoadJbs", ReplyAction="http://aeseg.isciii.es/IJustification/LoadJbsResponse")]
        ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult LoadJbs(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JbsInterchageModel jbs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/LoadJbs", ReplyAction="http://aeseg.isciii.es/IJustification/LoadJbsResponse")]
        System.Threading.Tasks.Task<ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult> LoadJbsAsync(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JbsInterchageModel jbs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/LoadJpersonal", ReplyAction="http://aeseg.isciii.es/IJustification/LoadJpersonalResponse")]
        ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult LoadJpersonal(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JpersonalInterchageModel jpersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/LoadJpersonal", ReplyAction="http://aeseg.isciii.es/IJustification/LoadJpersonalResponse")]
        System.Threading.Tasks.Task<ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult> LoadJpersonalAsync(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JpersonalInterchageModel jpersonal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/LoadJviajes", ReplyAction="http://aeseg.isciii.es/IJustification/LoadJviajesResponse")]
        ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult LoadJviajes(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JviajeInterchageModel jviaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/LoadJviajes", ReplyAction="http://aeseg.isciii.es/IJustification/LoadJviajesResponse")]
        System.Threading.Tasks.Task<ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult> LoadJviajesAsync(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JviajeInterchageModel jviaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/GetVersion", ReplyAction="http://aeseg.isciii.es/IJustification/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/GetVersion", ReplyAction="http://aeseg.isciii.es/IJustification/GetVersionResponse")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/Test", ReplyAction="http://aeseg.isciii.es/IJustification/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://aeseg.isciii.es/IJustification/Test", ReplyAction="http://aeseg.isciii.es/IJustification/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJustificationChannel : ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.IJustification, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JustificationClient : System.ServiceModel.ClientBase<ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.IJustification>, ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.IJustification {
        
        public JustificationClient() {
        }
        
        public JustificationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JustificationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JustificationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JustificationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult LoadJbs(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JbsInterchageModel jbs) {
            return base.Channel.LoadJbs(jbs);
        }
        
        public System.Threading.Tasks.Task<ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult> LoadJbsAsync(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JbsInterchageModel jbs) {
            return base.Channel.LoadJbsAsync(jbs);
        }
        
        public ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult LoadJpersonal(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JpersonalInterchageModel jpersonal) {
            return base.Channel.LoadJpersonal(jpersonal);
        }
        
        public System.Threading.Tasks.Task<ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult> LoadJpersonalAsync(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JpersonalInterchageModel jpersonal) {
            return base.Channel.LoadJpersonalAsync(jpersonal);
        }
        
        public ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult LoadJviajes(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JviajeInterchageModel jviaje) {
            return base.Channel.LoadJviajes(jviaje);
        }
        
        public System.Threading.Tasks.Task<ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.LoadResult> LoadJviajesAsync(ISCIII.AESEG.ClienteJustificacion.Proxy.ProxyJustificacion.JviajeInterchageModel jviaje) {
            return base.Channel.LoadJviajesAsync(jviaje);
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync() {
            return base.Channel.GetVersionAsync();
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
    }
}
